# fly.toml app configuration file generated for abd-be-ts on 2023-08-10T17:40:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "abd-be-ts"
primary_region = "bos"

[env]
  PORT= "8080"
  DEBUG = "loopback:connector*"

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]


  [[http_service.checks]]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/ping"


