# fly.toml app configuration file generated for abd-be-ts on 2023-08-10T17:40:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "abd-be-ts"
primary_region = "bos"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
